
// This file was generated by Firebase Studio
// Learn more about this file at https://www.notion.so/firebase-studio/Code-your-app-with-the-help-of-AI-447543ee9e544ad28634356c93170701#9f713e5f22574e92ad32c798363c3d52
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  apiKey: "AIzaSyCSoVvRQpuyN8QB0ThpKpVsxl0x38BgZEE",
  authDomain: "tactical-tic-tac-toe-online.firebaseapp.com",
  projectId: "tactical-tic-tac-toe-online",
  storageBucket: "tactical-tic-tac-toe-online.firebasestorage.app",
  messagingSenderId: "398036169929",
  appId: "1:398036169929:web:603ae734e6e2e639c74918"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);
const auth = getAuth(app);

export { db, auth, app };
